version: "3.7"
services:
 # Banco de dados usado pela aplicacao
 mysql:
  container_name: mysql_Right_Shot_Club
  image: mysql:latest 
  environment:
   MYSQL_ROOT_PASSWORD: root
   MYSQL_DATABASE: "rightshot"
  ports:
   - 3306:3306

 sonarqube:
  container_name: sonarqube_rightShotClub
  image: sonarqube:community
  depends_on:
   - db
  environment:
   SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
   SONAR_JDBC_USERNAME: sonar
   SONAR_JDBC_PASSWORD: sonar
  volumes:
   - sonarqube_data:/opt/sonarqube/data
   - sonarqube_extensions:/opt/sonarqube/extensions
   - sonarqube_logs:/opt/sonarqube/logs
  ports:
   - "9000:9000"

 db:
  container_name: postgres_sonarqube_rightShotClub
  image: postgres
  environment:
   POSTGRES_USER: sonar
   POSTGRES_PASSWORD: sonar
  volumes:
   - postgresql:/var/lib/postgresql
   - postgresql_data:/var/lib/postgresql/data
  ports:
   - 5432:5432

 grafana:
  image: grafana/grafana:latest
  container_name: grafana_rightShotClub
  restart: always
  ports:
   - 3000:3000
  networks:
   - grafana_network
  environment:
   - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
   - GF_AUTH_ANONYMOUS_ENABLED=true
   - GF_AUTH_BASIC_ENABLED=false
  volumes:
   - grafana_data:/var/lib/grafana
  depends_on:
   - influxdb

 influxdb:
  image: influxdb:1.8
  container_name: influxdb_grafana_rightShotClub
  restart: always
  ports:
   - 8086:8086
   - 8082:8082
  networks:
   - grafana_network
  volumes:
   - influxdb_data:/var/lib/influxdb
  environment:
   - INFLUXDB_DB=grafana
   - INFLUXDB_USER=grafana
   - INFLUXDB_USER_PASSWORD=password
   - INFLUXDB_ADMIN_ENABLED=true
   - INFLUXDB_ADMIN_USER=admin
   - INFLUXDB_ADMIN_PASSWORD=password

 k6:
  container_name: k6_rightShotClub
  image: loadimpact/k6:latest
  networks:
   - grafana_network
  ports:
   - "6565:6565"
  environment:
   - K6_OUT=influxdb=http://influxdb:8086/grafana
  volumes:
   - ./scripts:/scripts

networks:
 grafana_network:

volumes:
 sonarqube_data:
  driver: local
 sonarqube_extensions:
 sonarqube_logs:
 postgresql:
 postgresql_data:
  driver: local
 grafana_data:
 influxdb_data: