version: "3.7"
services:
 # Banco de dados usado pela aplicacao
 mysql:
  container_name: mysql_Right_Shot_Club
  image: mysql:latest 
  environment:
   MYSQL_ROOT_PASSWORD: root
   MYSQL_DATABASE: "rightshot"
  ports:
   - 3306:3306